---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tao-guardian-io-v1alpha1-taonode
  failurePolicy: Fail
  name: vtaonode.kb.io
  rules:
  - apiGroups:
    - tao.guardian.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - taonodes
  sideEffects: None
