apiVersion: v1
kind: ServiceAccount
metadata:
  name: taonode-guardian-controller-manager
  namespace: taonode-guardian-system
  labels:
    app.kubernetes.io/name: taonode-guardian
    app.kubernetes.io/component: controller-manager
