//go:build !ignore_autogenerated

/*
Copyright 2026 Claudio Botelho.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAdvisorSpec) DeepCopyInto(out *AIAdvisorSpec) {
	*out = *in
	if in.NotificationChannels != nil {
		in, out := &in.NotificationChannels, &out.NotificationChannels
		*out = new(NotificationChannels)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAdvisorSpec.
func (in *AIAdvisorSpec) DeepCopy() *AIAdvisorSpec {
	if in == nil {
		return nil
	}
	out := new(AIAdvisorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAdvisoryStatus) DeepCopyInto(out *AIAdvisoryStatus) {
	*out = *in
	if in.LastReport != nil {
		in, out := &in.LastReport, &out.LastReport
		*out = new(AIIncidentReportStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAdvisoryStatus.
func (in *AIAdvisoryStatus) DeepCopy() *AIAdvisoryStatus {
	if in == nil {
		return nil
	}
	out := new(AIAdvisoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIIncidentReportStatus) DeepCopyInto(out *AIIncidentReportStatus) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIIncidentReportStatus.
func (in *AIIncidentReportStatus) DeepCopy() *AIIncidentReportStatus {
	if in == nil {
		return nil
	}
	out := new(AIIncidentReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertRule) DeepCopyInto(out *AlertRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertRule.
func (in *AlertRule) DeepCopy() *AlertRule {
	if in == nil {
		return nil
	}
	out := new(AlertRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSpec) DeepCopyInto(out *AnalyticsSpec) {
	*out = *in
	out.ClickHouseRef = in.ClickHouseRef
	out.Ingestion = in.Ingestion
	if in.AnomalyDetection != nil {
		in, out := &in.AnomalyDetection, &out.AnomalyDetection
		*out = new(AnomalyDetectionSpec)
		**out = **in
	}
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsSpec.
func (in *AnalyticsSpec) DeepCopy() *AnalyticsSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsStatusBlock) DeepCopyInto(out *AnalyticsStatusBlock) {
	*out = *in
	if in.LastIngestionTime != nil {
		in, out := &in.LastIngestionTime, &out.LastIngestionTime
		*out = (*in).DeepCopy()
	}
	if in.AnomalyScores != nil {
		in, out := &in.AnomalyScores, &out.AnomalyScores
		*out = make([]AnomalyScoreStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsStatusBlock.
func (in *AnalyticsStatusBlock) DeepCopy() *AnalyticsStatusBlock {
	if in == nil {
		return nil
	}
	out := new(AnalyticsStatusBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyDetectionSpec) DeepCopyInto(out *AnomalyDetectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyDetectionSpec.
func (in *AnomalyDetectionSpec) DeepCopy() *AnomalyDetectionSpec {
	if in == nil {
		return nil
	}
	out := new(AnomalyDetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyScoreStatus) DeepCopyInto(out *AnomalyScoreStatus) {
	*out = *in
	if in.DetectedAt != nil {
		in, out := &in.DetectedAt, &out.DetectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyScoreStatus.
func (in *AnomalyScoreStatus) DeepCopy() *AnomalyScoreStatus {
	if in == nil {
		return nil
	}
	out := new(AnomalyScoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoExpandSpec) DeepCopyInto(out *AutoExpandSpec) {
	*out = *in
	out.MaxSize = in.MaxSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoExpandSpec.
func (in *AutoExpandSpec) DeepCopy() *AutoExpandSpec {
	if in == nil {
		return nil
	}
	out := new(AutoExpandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDBackupSpec) DeepCopyInto(out *CRDBackupSpec) {
	*out = *in
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDBackupSpec.
func (in *CRDBackupSpec) DeepCopy() *CRDBackupSpec {
	if in == nil {
		return nil
	}
	out := new(CRDBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainDataDRSpec) DeepCopyInto(out *ChainDataDRSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainDataDRSpec.
func (in *ChainDataDRSpec) DeepCopy() *ChainDataDRSpec {
	if in == nil {
		return nil
	}
	out := new(ChainDataDRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainStatus) DeepCopyInto(out *ChainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainStatus.
func (in *ChainStatus) DeepCopy() *ChainStatus {
	if in == nil {
		return nil
	}
	out := new(ChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainStorageSpec) DeepCopyInto(out *ChainStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.AutoExpand != nil {
		in, out := &in.AutoExpand, &out.AutoExpand
		*out = new(AutoExpandSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainStorageSpec.
func (in *ChainStorageSpec) DeepCopy() *ChainStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ChainStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseDRSpec) DeepCopyInto(out *ClickHouseDRSpec) {
	*out = *in
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseDRSpec.
func (in *ClickHouseDRSpec) DeepCopy() *ClickHouseDRSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseDRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseRef) DeepCopyInto(out *ClickHouseRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseRef.
func (in *ClickHouseRef) DeepCopy() *ClickHouseRef {
	if in == nil {
		return nil
	}
	out := new(ClickHouseRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecoverySpec) DeepCopyInto(out *DisasterRecoverySpec) {
	*out = *in
	out.CRDBackup = in.CRDBackup
	out.ChainDataDR = in.ChainDataDR
	if in.ClickHouseDR != nil {
		in, out := &in.ClickHouseDR, &out.ClickHouseDR
		*out = new(ClickHouseDRSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecoverySpec.
func (in *DisasterRecoverySpec) DeepCopy() *DisasterRecoverySpec {
	if in == nil {
		return nil
	}
	out := new(DisasterRecoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSpec) DeepCopyInto(out *GPUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSpec.
func (in *GPUSpec) DeepCopy() *GPUSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionSpec) DeepCopyInto(out *IngestionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionSpec.
func (in *IngestionSpec) DeepCopy() *IngestionSpec {
	if in == nil {
		return nil
	}
	out := new(IngestionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.AlertRules != nil {
		in, out := &in.AlertRules, &out.AlertRules
		*out = make([]AlertRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationChannels) DeepCopyInto(out *NotificationChannels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationChannels.
func (in *NotificationChannels) DeepCopy() *NotificationChannels {
	if in == nil {
		return nil
	}
	out := new(NotificationChannels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	if in.GPUUtilizationPercent != nil {
		in, out := &in.GPUUtilizationPercent, &out.GPUUtilizationPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDestination) DeepCopyInto(out *SnapshotDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDestination.
func (in *SnapshotDestination) DeepCopy() *SnapshotDestination {
	if in == nil {
		return nil
	}
	out := new(SnapshotDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotPolicySpec) DeepCopyInto(out *SnapshotPolicySpec) {
	*out = *in
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotPolicySpec.
func (in *SnapshotPolicySpec) DeepCopy() *SnapshotPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStatus) DeepCopyInto(out *SnapshotStatus) {
	*out = *in
	if in.LastSnapshotTime != nil {
		in, out := &in.LastSnapshotTime, &out.LastSnapshotTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStatus.
func (in *SnapshotStatus) DeepCopy() *SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicySpec) DeepCopyInto(out *SyncPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicySpec.
func (in *SyncPolicySpec) DeepCopy() *SyncPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SyncPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStateStatus) DeepCopyInto(out *SyncStateStatus) {
	*out = *in
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStateStatus.
func (in *SyncStateStatus) DeepCopy() *SyncStateStatus {
	if in == nil {
		return nil
	}
	out := new(SyncStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaoNode) DeepCopyInto(out *TaoNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaoNode.
func (in *TaoNode) DeepCopy() *TaoNode {
	if in == nil {
		return nil
	}
	out := new(TaoNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaoNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaoNodeList) DeepCopyInto(out *TaoNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaoNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaoNodeList.
func (in *TaoNodeList) DeepCopy() *TaoNodeList {
	if in == nil {
		return nil
	}
	out := new(TaoNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaoNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaoNodeSpec) DeepCopyInto(out *TaoNodeSpec) {
	*out = *in
	in.ChainStorage.DeepCopyInto(&out.ChainStorage)
	out.SyncPolicy = in.SyncPolicy
	if in.SnapshotPolicy != nil {
		in, out := &in.SnapshotPolicy, &out.SnapshotPolicy
		*out = new(SnapshotPolicySpec)
		**out = **in
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUSpec)
		**out = **in
	}
	if in.Validator != nil {
		in, out := &in.Validator, &out.Validator
		*out = new(ValidatorSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Analytics != nil {
		in, out := &in.Analytics, &out.Analytics
		*out = new(AnalyticsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AIAdvisor != nil {
		in, out := &in.AIAdvisor, &out.AIAdvisor
		*out = new(AIAdvisorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DisasterRecovery != nil {
		in, out := &in.DisasterRecovery, &out.DisasterRecovery
		*out = new(DisasterRecoverySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaoNodeSpec.
func (in *TaoNodeSpec) DeepCopy() *TaoNodeSpec {
	if in == nil {
		return nil
	}
	out := new(TaoNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaoNodeStatus) DeepCopyInto(out *TaoNodeStatus) {
	*out = *in
	in.SyncState.DeepCopyInto(&out.SyncState)
	out.Chain = in.Chain
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Analytics != nil {
		in, out := &in.Analytics, &out.Analytics
		*out = new(AnalyticsStatusBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.AIAdvisory != nil {
		in, out := &in.AIAdvisory, &out.AIAdvisory
		*out = new(AIAdvisoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaoNodeStatus.
func (in *TaoNodeStatus) DeepCopy() *TaoNodeStatus {
	if in == nil {
		return nil
	}
	out := new(TaoNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorSpec) DeepCopyInto(out *ValidatorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorSpec.
func (in *ValidatorSpec) DeepCopy() *ValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ValidatorSpec)
	in.DeepCopyInto(out)
	return out
}
