apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  labels:
    app.kubernetes.io/name: taonode-guardian-clickhouse
    app.kubernetes.io/part-of: taonode-guardian
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ClaudioBotelhOSB/taonode-guardian
    targetRevision: HEAD
    path: config/clickhouse

  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
